=== fhildeb/ba-data-representation/2-dtd-based-xml/measurements.dtd
<!ELEMENT messberichte (messbericht+)>
			<!ELEMENT messbericht (kopfdaten, messwertdaten, pruefergebnis)>
			<!-- Kopfdaten DATA-->
				<!ELEMENT kopfdaten (artikeldaten, lieferantendaten, prueferdaten)>
					<!ELEMENT artikeldaten (zeichnungsnummer, bezeichnung)>
						<!ELEMENT zeichnungsnummer (#PCDATA)>
						<!ELEMENT bezeichnung (#PCDATA)>
						
					<!ELEMENT lieferantendaten (lieferant)>
						<!ELEMENT lieferant (#PCDATA)>

						<!ELEMENT prueferdaten (pruefer)>
							<!ELEMENT pruefer (arbeitszeitverbrauch)>
								<!ELEMENT arbeitszeitverbrauch (#PCDATA)>
			<!-- Messwertdaten DATA-->		
				<!ELEMENT messwertdaten (pruefmerkmal+)>
					<!ELEMENT pruefmerkmal (messwert+, mittelwert)>
						<!ELEMENT messwert (#PCDATA)>
						<!ELEMENT mittelwert (#PCDATA)>
						
			<!-- Pruefergebnis DATA-->		
				<!ELEMENT pruefergebnis (bemerkung, nachbearbeitungstermin?)>
					<!ELEMENT bemerkung (#PCDATA)>
					<!ELEMENT nachbearbeitungstermin (#PCDATA)>
			
			<!-- Kopfdaten ATTRIBUTES-->
				<!ENTITY % id_short "ID #REQUIRED" >
				<!ATTLIST messbericht messbericht_id %id_short;>
				<!ATTLIST messbericht datum CDATA #REQUIRED>
					<!ATTLIST artikeldaten artikel_id CDATA #REQUIRED>
					<!ATTLIST lieferantendaten lieferanten_id CDATA #REQUIRED>
					<!ATTLIST prueferdaten pruefplan_id CDATA #REQUIRED>
						<!ATTLIST pruefer link CDATA #REQUIRED>
				
			<!-- Messwertdaten ATTRIBUTES-->
				<!ATTLIST pruefmerkmal name CDATA #REQUIRED>
				<!ATTLIST pruefmerkmal dimension CDATA #REQUIRED>
					<!ATTLIST messwert lfd_nr CDATA #REQUIRED>
					
			<!-- Pruefergebnis ATTRIBUTES-->
			<!ATTLIST pruefergebnis einstufung CDATA #REQUIRED>

=== fhildeb/ba-data-representation/2-dtd-based-xml/measurements.xml
<?xml version="1.0" encoding = "ISO-8859-1" standalone="no" ?>
<!DOCTYPE messberichte SYSTEM "./measurements.dtd" >
		
<messberichte>
	<messbericht messbericht_id = "YXZ-0815" datum="27.09.2018">
	
		<!-- Kopfdaten -->
		<kopfdaten>
			<artikeldaten artikel_id="wz-123-876">
				<zeichnungsnummer>tpb7012578-v01</zeichnungsnummer>
				<bezeichnung>CPU-Kuehlkoerper A1</bezeichnung>
			</artikeldaten>
			<lieferantendaten lieferanten_id="L00304">
				<lieferant>Fischer AG, Ulm</lieferant>
			</lieferantendaten>
			<prueferdaten pruefplan_id="wz-213-876-ppll">
				<pruefer link="stefan@abcd.com">
					<arbeitszeitverbrauch>4.5 Stunden</arbeitszeitverbrauch>
				</pruefer>
			</prueferdaten>
		</kopfdaten>
		
		<!-- Messwertdaten -->
		<messwertdaten>
			<pruefmerkmal name="laenge-a" dimension="mm">
				<messwert lfd_nr="1" >50,12</messwert>
				<messwert lfd_nr="2" >50,01</messwert>
				<messwert lfd_nr="3" >49,98</messwert>
				<mittelwert>50,04</mittelwert>
			</pruefmerkmal>
			
			<pruefmerkmal name="gesamtmasse" dimension="g">
				<messwert lfd_nr="1" >210,3</messwert>
				<messwert lfd_nr="2" >209,8</messwert>
				<messwert lfd_nr="3" >208,9</messwert>
				<mittelwert>209,7</mittelwert>
			</pruefmerkmal>
		</messwertdaten>
		
		<!-- Pruefergebnis -->
		<pruefergebnis einstufung="Nacharbeit">
			<bemerkung>
			Die Pruef-Ergebnisse liegen in einem Grenzbereich, dass der
			o.g. Artikel mit einer speziellen Nacharbeit XYZ einer erneuten Pruefung
			unterzogen werden kann.
			</bemerkung>
			<nachbearbeitungstermin>25.10.2018</nachbearbeitungstermin>
		</pruefergebnis>
	</messbericht>
</messberichte>
