=== fhildeb/ba-data-representation/6-sax-xml-parsing/template/addresses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tcaq_Adressen" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tcaq_Adressen">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="FIRMA" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="STRASSE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="PLZ" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="5"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ORT" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LAND" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="3"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TELEFON" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TELEFAX" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ERSTKONTAKT" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="WIEDERVORLAGE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="ANZ_MITARBEITER" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="LINK" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== fhildeb/ba-data-representation/6-sax-xml-parsing/template/addresses-shortened.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="FirmenAdressen.xsl"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="addresses.xsd" generated="2007-04-15T18:10:53">
<tcaq_Adressen>
<ID>1</ID>
<FIRMA>Per Cent Maschinenbau AG</FIRMA>
<STRASSE>Luisenstraße 96</STRASSE>
<PLZ>45229</PLZ>
<ORT>Essen</ORT>
<LAND>D</LAND>
<TELEFON>0 13659 /  872884</TELEFON>
<TELEFAX>0 13659 /  872884</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>21</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>2</ID>
<FIRMA>Felgner Black &amp; White GmbH</FIRMA>
<STRASSE>Wilhelmplatz 127</STRASSE>
<PLZ>45272</PLZ>
<ORT>Essen</ORT>
<LAND>D</LAND>
<TELEFON>0 9425 /  530795</TELEFON>
<TELEFAX>0 9425 /  530795</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>3</ID>
<FIRMA>SCHULZE Kabelfertigung GmbH</FIRMA>
<STRASSE>Weststraße 108</STRASSE>
<PLZ>07924</PLZ>
<ORT>Greiz</ORT>
<LAND>D</LAND>
<TELEFON>0 60501 /  441218</TELEFON>
<TELEFAX>0 60501 /  441218</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>34</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>4</ID>
<FIRMA>Görner Black &amp; White GmbH</FIRMA>
<STRASSE>Kirchstraße 43</STRASSE>
<PLZ>07826</PLZ>
<ORT>Triptis</ORT>
<LAND>D</LAND>
<TELEFON>0 65792 /  850761</TELEFON>
<TELEFAX>0 65792 /  850761</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>5</ID>
<FIRMA>TERACLEAN GmbH &amp; Co. KG</FIRMA>
<STRASSE>Weststraße 9</STRASSE>
<PLZ>29542</PLZ>
<ORT>Uelzen</ORT>
<LAND>D</LAND>
<TELEFON>0 54710 /  270124</TELEFON>
<TELEFAX>0 54710 /  270124</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>45</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>6</ID>
<FIRMA>SCHMIDT Sicherungstechnik GmbH</FIRMA>
<STRASSE>Luisenstraße 36</STRASSE>
<PLZ>06140</PLZ>
<ORT>Halle</ORT>
<LAND>D</LAND>
<TELEFON>0 25195 /  745236</TELEFON>
<TELEFAX>0 25195 /  745236</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>7</ID>
<FIRMA>Langer Elektronik GmbH</FIRMA>
<STRASSE>Luisenplatz 174</STRASSE>
<PLZ>09569</PLZ>
<ORT>Freiberg</ORT>
<LAND>D</LAND>
<TELEFON>0 46117 /  499013</TELEFON>
<TELEFAX>0 46117 /  499013</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>8</ID>
<FIRMA>Schönherr GmbH &amp; Co. KG</FIRMA>
<STRASSE>Kirchstraße 69</STRASSE>
<PLZ>99813</PLZ>
<ORT>Ifta</ORT>
<LAND>D</LAND>
<TELEFON>0 41351 /  836571</TELEFON>
<TELEFAX>0 41351 /  836571</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>9</ID>
<FIRMA>Oehme Blechteile KG</FIRMA>
<STRASSE>Parkstraße 29</STRASSE>
<PLZ>09173</PLZ>
<ORT>Chemnitz</ORT>
<LAND>D</LAND>
<TELEFON>0 89473 /  542075</TELEFON>
<TELEFAX>0 89473 /  542075</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>10</ID>
<FIRMA>Görner Bauelemente GmbH</FIRMA>
<STRASSE>Friedrichstraße 21</STRASSE>
<PLZ>07972</PLZ>
<ORT>Zeulenroda</ORT>
<LAND>D</LAND>
<TELEFON>0 64179 /  624005</TELEFON>
<TELEFAX>0 64179 /  624005</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>11</ID>
<FIRMA>Fiedler GmbH &amp; Co. KG</FIRMA>
<STRASSE>Sonnenstraße 46</STRASSE>
<PLZ>72599</PLZ>
<ORT>Hülben</ORT>
<LAND>D</LAND>
<TELEFON>0 75111 /  207044</TELEFON>
<TELEFAX>0 75111 /  207044</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>123</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>12</ID>
<FIRMA>Reichel Rückhaltesysteme GmbH</FIRMA>
<STRASSE>Mozartstraße 113</STRASSE>
<PLZ>16306</PLZ>
<ORT>Schönow</ORT>
<LAND>D</LAND>
<TELEFON>0 8843 /  732911</TELEFON>
<TELEFAX>0 8843 /  732911</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>13</ID>
<FIRMA>Haak Halbleiter GmbH</FIRMA>
<STRASSE>Rathausstraße 24</STRASSE>
<PLZ>99837</PLZ>
<ORT>Thal</ORT>
<LAND>D</LAND>
<TELEFON>0 59972 /  944788</TELEFON>
<TELEFAX>0 59972 /  944788</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>14</ID>
<FIRMA>Schönherr Elektronik GmbH</FIRMA>
<STRASSE>Nordstraße 66</STRASSE>
<PLZ>09656</PLZ>
<ORT>Hainichen</ORT>
<LAND>D</LAND>
<TELEFON>0 79755 /  419014</TELEFON>
<TELEFAX>0 79755 /  419014</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>15</ID>
<FIRMA>Lang network &amp; systems GmbH</FIRMA>
<STRASSE>Beispielgasse 117</STRASSE>
<PLZ>78010</PLZ>
<ORT>VS-Villingen</ORT>
<LAND>D</LAND>
<TELEFON>0 48832 /  172759</TELEFON>
<TELEFAX>0 48832 /  172759</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>16</ID>
<FIRMA>TERACLEAN Red &amp; Green GmbH</FIRMA>
<STRASSE>Sonnenstraße 67</STRASSE>
<PLZ>98682</PLZ>
<ORT>Hildburghausen</ORT>
<LAND>D</LAND>
<TELEFON>0 88601 /  134753</TELEFON>
<TELEFAX>0 88601 /  134753</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>17</ID>
<FIRMA>Möbius Blechteile KG</FIRMA>
<STRASSE>Parkstraße 146</STRASSE>
<PLZ>06769</PLZ>
<ORT>Bitterfeld</ORT>
<LAND>D</LAND>
<TELEFON>0 11094 /  520832</TELEFON>
<TELEFAX>0 11094 /  520832</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>18</ID>
<FIRMA>Haustein Kontronik GmbH</FIRMA>
<STRASSE>Parkstraße 184</STRASSE>
<PLZ>06168</PLZ>
<ORT>Halle</ORT>
<LAND>D</LAND>
<TELEFON>0 49043 /  732409</TELEFON>
<TELEFAX>0 49043 /  732409</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>11</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>19</ID>
<FIRMA>Arnold Banini GmbH</FIRMA>
<STRASSE>Weststraße 124</STRASSE>
<PLZ>60498</PLZ>
<ORT>Frankfurt/Main</ORT>
<LAND>D</LAND>
<TELEFON>0 74101 /  150715</TELEFON>
<TELEFAX>0 74101 /  150715</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>5</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>20</ID>
<FIRMA>IDI Elektronik GmbH</FIRMA>
<STRASSE>Weststraße 145</STRASSE>
<PLZ>28874</PLZ>
<ORT>Achim</ORT>
<LAND>D</LAND>
<TELEFON>0 74664 /  209088</TELEFON>
<TELEFAX>0 74664 /  209088</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>21</ID>
<FIRMA>ASL Blechteile KG</FIRMA>
<STRASSE>Am Mühlberg 87</STRASSE>
<PLZ>04513</PLZ>
<ORT>Rackwitz</ORT>
<LAND>D</LAND>
<TELEFON>0 8876 /  37926</TELEFON>
<TELEFAX>0 8876 /  37926</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>22</ID>
<FIRMA>ABC Logistik GbR</FIRMA>
<STRASSE>Kalkstraße 45</STRASSE>
<PLZ>01934</PLZ>
<ORT>Großröhrsdorf</ORT>
<LAND>D</LAND>
<TELEFON>0 98468 /  13063</TELEFON>
<TELEFAX>0 98468 /  13063</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>23</ID>
<FIRMA>IDD Economic GbR</FIRMA>
<STRASSE>Eisenweg 101</STRASSE>
<PLZ>35024</PLZ>
<ORT>Battenberg</ORT>
<LAND>D</LAND>
<TELEFON>0 91382 /  62710</TELEFON>
<TELEFAX>0 91382 /  62710</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>20</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>24</ID>
<FIRMA>Zimmermann Sicherungstechnik GmbH</FIRMA>
<STRASSE>Siemensstraße 145</STRASSE>
<PLZ>88613</PLZ>
<ORT>Überlingen</ORT>
<LAND>D</LAND>
<TELEFON>0 88190 /  149991</TELEFON>
<TELEFAX>0 88190 /  149991</TELEFAX>
<ERSTKONTAKT>2005-02-11T00:00:00</ERSTKONTAKT>
<WIEDERVORLAGE>2006-12-14T00:00:00</WIEDERVORLAGE>
<ANZ_MITARBEITER>2</ANZ_MITARBEITER>
</tcaq_Adressen>
<tcaq_Adressen>
<ID>25</ID>
<FIRMA>Schreiter Lenkrad GmbH</FIRMA>
<STRASSE>Neustädter Straße 188</STRASSE>
<PLZ>07922</PLZ>
<ORT>Greiz</ORT>
<LAND>D</LAND>
<TELEFON>0 84435 /  781647</TELEFON>
<TELEFAX>0 84435 /  781647</TELEFAX>
